### ISSUE TITLE
Road Map - Feature Request - Responsive Theme

### ISSUE THREAD

**Issue by HyperGlide** [rotarytheme/rotary#1]
Hello,

I had sent an email earlier in the week introducing myself and the Rotary Club of Chengdu.

We are excited about getting involved and supporting this project.

We are already moving our existing site to your WP Rotary Theme / Plugin.

I would like to know if you have a roadmap of new features?

We would love to see the site have a responsive theme for mobile devices.

Many thanks and look forward to your reply.

Hg

**Comment by rotarytheme** [comment]
Yes - responsiveness is the next think on the roadmap!

................................

Paul Osborn

Bellevue Breakfast Rotary Club

Tel 1.425.605.7707

Skype paosborn

bbrc.nethttp://bbrc.net/

[unknown.png]

**Comment by HyperGlide** [comment]
Thank you Paul!

If there is anything we can do here in Chengdu, China please let me know. 

Kind regards,
 Harley

**Comment by rotarytheme** [comment]
Awesome - I'm not about to turn down an offer of help....

We are actually not sure at the moment what approach we will take to turn the site responsive.  For example, we are wondering if we should just create a stripped-down mobile version, and in any case, what components would be important to have in the mobile version.

Depending on what skills you have access to, we are very happy to entertain design/layout suggestions, technology/architecture suggestions, or even coding contributions (the site is on gitub)

................................

Paul Osborn

Bellevue Breakfast Rotary Club

Tel 1.425.605.7707

Skype paosborn

bbrc.nethttp://bbrc.net/

[unknown.png]

**Comment by HyperGlide** [comment]
Hi Paul!

Great! With regards to this work my skills align mostly in UX, UI, testing, PM, SEO / SEM, CSS, etc. Not really a coder but I have written some PHP.

For the components in the mobile I can certainly share my ideas. Would you like to have that conversation here or in a new thread?

Are you doing most of the coding / dev work yourself?

Cheers,
 HG.

ps. if I can suggest you not respond with your footer it would be helpful ;-) makes the scroll back much longer on the page with it any my comments in your reply. 

pss. If you also like we can connect on Facebook or Skype.

P.s.s.s Are you yourself a Rotarian?

**Comment by rotarytheme** [comment]
Let' start a new thread - I just noticed you are going through github.  My direct email is rotary@paulosborn.com - so please email me directly, and yes, we are Rotarians.  I will loop the developer into the conversation on the new thread...

Paul

**Comment by HyperGlide** [comment]
Replied privately. Going to close this thread out. Great work guys!
