### ISSUE TITLE
Theme Settings Lost on Update

### ISSUE THREAD

**Issue by HyperGlide** [rotarytheme/rotary#3]
It seems that each time we update the theme the settings for the theme are lost and need to be reset at "/wp-admin/customize.php"

This happens before the plugin is updated. 

It does not take long to put all things back in place but is this occurring on other sites?

**Comment by rotarytheme** [comment]
Yes - it is strange - we haven't managed to figure this out ourselves...sorry about that !

................................

Paul Osborn

Bellevue Breakfast Rotary Club

Tel 1.425.605.7707

Skype paosborn

bbrc.nethttp://bbrc.net/

[unknown.png]

**Comment by HyperGlide** [comment]
Okay latest is happening to more than just us. :-)

**Comment by posborn001002** [comment]
The fix you put in place is more or less working, but we should make it smarter (triggered only on theme update, rather than all the time....)
