### ISSUE TITLE
Rotary - Reference Document

### ISSUE THREAD

**Issue by HyperGlide** [rotarytheme/rotary#4]
Hello,

This was passed to me by Special Representative to China, PP Randal Eastman

It is the "QUICK START GUIDE FOR CLUB WEBSITES" from R.I.

https://www.rotary.org/myrotary/en/find-digital-guidelines-your-club-website-rotarys-brand-center

**Comment by rotarytheme** [comment]
Thanks for this - I agree, and something else on our list is  to tweak the styling to conform to these standards a bit more.  We started the project several years ago, before the new branding initiative, and although have done some tweaks, have not revisited the design.  There are also some good ideas for page content/layout in here - looking at it, I should probably update bbrcwebsite.com ...

................................

Paul Osborn

Bellevue Breakfast Rotary Club

Tel 1.425.605.7707

Skype paosborn

bbrc.nethttp://bbrc.net/

[unknown.png]

**Comment by HyperGlide** [comment]
Glad to get the positive feedback. Please let me know if you want any specific suggestions. 

Perhaps it would be best to look at this before the responsive element we discussed last week.

**Comment by posborn001002** [comment]
The latest version (4+) are compliant with these guidelines, and/or these guidelines and the styling set by Rotary.org as of 2015
