### ISSUE TITLE
Trying to translate in French but the .po files seems ignored (English and French as well)

### ISSUE THREAD

**Issue by bligneri** [rotarytheme/rotary#54]
I would like to translate in french the theme.
Wordpress 4.6 latest version.

In wordpress/wp-content/themes/rotary-master/languages
I created a fr_CA.pot file to no effect.

I then tried to modify the en_EN.pot

However, it looks like this file is not used.

Any idea what I should do to activate the translation and translate the them for french usage?

**Comment by bligneri** [comment]
Also posted in the support forum : http://bbrcwebsite.com/forums/topic/trying-to-translate-in-french-but-the-po-files-seems-ignored-english-and-frenc/

**Comment by rotarytheme** [comment]
Use these.

................................

Paul Osborn

DECA Committee Chair

Website Committee Chair

Bellevue Breakfast Rotary Club

Tel 1.425.605.7707

Skype paosborn

bbrc.nethttp://bbrc.net/

[unknown.png]

**Comment by rotarytheme** [comment]
Email me directly at bbrcwebmaster@bbrc.net

................................

Paul Osborn

DECA Committee Chair

Website Committee Chair

Bellevue Breakfast Rotary Club

Tel 1.425.605.7707

Skype paosborn

bbrc.nethttp://bbrc.net/

[unknown.png]

**Comment by rotarytheme** [comment]
webmaster@bbrc.net

Whoops!

From: Paul Osborn <paul_o@paulosborn.com<mailto:paul_o@paulosborn.com>>
Date: Friday, August 26, 2016 at 11:22 PM
To: rotarytheme/rotary <reply@reply.github.com<mailto:reply@reply.github.com>>, rotarytheme/rotary <rotary@noreply.github.com<mailto:rotary@noreply.github.com>>
Subject: Re: [rotarytheme/rotary] Try to install on 4.6 but does not work (#54)

Email me directly at bbrcwebmaster@bbrc.netmailto:bbrcwebmaster@bbrc.net

................................

Paul Osborn

DECA Committee Chair

Website Committee Chair

Bellevue Breakfast Rotary Club

Tel 1.425.605.7707

Skype paosborn

bbrc.nethttp://bbrc.net/

[unknown.png]
